#!/usr/bin/env bash
#
#
PEPE="/etc/passwd"

while IFS=":" read -r user pw uid gid uinfo homedir shell
do
	echo "The user $user is part of the $gid gang, lives in $homedir and $IFS 
		rides $shell. $uid's place is protected by the passcode $pw, $IFS
		more info about the user here: $uinfo"
done < $PEPE
