#!/usr/bin/env bash
#
#
PEPE1=0
PEPE2=10

while [ $PEPE1 -lt $PEPE2 ]
do
	if [ $PEPE1 -eq 3 ]
	then
		echo "bad luck"
	elif [ $PEPE1 -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((PEPE1++))
done

