#!/usr/bin/env bash
#
PEPE_M1=1
PEPE_M2=59
PEPE_H1=0
PEPE_H2=12

while [ $PEPE_H1 -le $PEPE_H2 ]
do
	echo "Hour: $PEPE_H1"

	while [ $PEPE_M1 -le $PEPE_M2 ]
	do
		echo "$PEPE_M1"
		((PEPE_M1++))
	done
	((PEPE_M1=1))
	((PEPE_H1++))
done
