#!/usr/bin/env bash
#
#
PEPE="school"

if [ -e "$FILE" ]
then
	echo "school file exists"

        if [ ! -s "$PEPE" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$PEPE" ]
	then
		echo "school is a regular file"
	else
	fi

	echo "school file does not exist"
fi
