#!/usr/bin/env bash
#
#
PEPE="school"

if [ -a "$PEPE" ]
then
	echo "school file exists"

        if [ -s "$PEPE" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$PEPE" ]
	then
		echo "school is a regular file"
	fi
	
else
	echo "school file does not exist"	
fi
