#!/usr/bin/env bash
#
#
PEPE1=1
PEPE2=1

echo $$ > /var/run/myscript.pid

sudo

while [ $PEPE1 -eq $PEPE2 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
        trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
