#!/usr/bin/env bash
#
#
PEPE1=1
PEPE2=1

echo $BASHPID > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?"' SIGINT
trap 'rm /var/run/myscrit.pid' SIGQUIT

while [ $PEPE1 -eq $PEPE2 ]
do
	echo "To infinity and beyond"
	sleep 2
done
