#!/usr/bin/env bash
#
#
PEPE="manage_my_process"

if [ "${1}" == "start" ]
then
	./manage_my_process &
	echo "$!" >> /var/run/my_process.pid
	echo "$PEPE started"

elif [ "${1}" == "stop" ]
then
	kill "$!"
	rm "/var/run/my_process.pid"
	echo "$PEPE stopped"

elif [ "${1}" == "restart" ]
then
	kill "$!"
	rm "/var/run/my_process.pid"
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "$PEPE restarted"
else
	echo 'Usage: manage_my_process {start|stop|restart}'
fi
